### PR TITLE
Hello rule-engine, goodbye classifier

### PR DESCRIPTION
**Pull request by VictorLowther**

### CODE REVIEW

**Comment by galthaus** [comment]
How do we load in "default" rule sets?

**Comment by VictorLowther** [comment]
Well, that is why you probably shouldn't merge it yet. :)

**Comment by VictorLowther** [comment]
This is mainly a milestone in that the service registers itself and deals with all the cert stuff properly for revproxy.

**Comment by galthaus** [comment]
I'll wait then.  :-)

**Comment by galthaus** [comment]
I think only heartbeat is currently using it.

**Comment by VictorLowther** [comment]
ok

**Pull request closed without merging**
